package:
  name: tjscan
  version: "0.0.1"
  epoch: 1
  description: Scan Workflow logs for IOCs from the tj-actions/changed-files breach
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/tj-scan
      expected-commit: 10f3937a7a56ef01cfbbd3ed6edece2d3c3cd673

  - uses: go/build
    with:
      packages: ./cmd/tj-scan
      output: tjscan

test:
  pipeline:
    - name: Verify tj-scan version
      runs: |
        tjscan -h
