package:
  name: tjscan
  version: "0.0.1"
  epoch: 1
  description: Scan Workflow logs for IOCs from the tj-actions/changed-files breach
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/egibs/tj-scan
      expected-commit: 8fd6b3108f6d18ab7f75492aa829df9ed537b03f

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.36.0

  - uses: go/build
    with:
      packages: ./cmd/tj-scan
      output: tjscan

test:
  pipeline:
    - name: Verify tj-sscan version
      runs: |
        tj-scan -h
