issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/tj-scan:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/tj-scan/.github/workflows/build.yaml@.*

permissions:
  contents: read
